/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.Formulario.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Registro service. Represents a row in the &quot;Registro_Registro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.Formulario.model.impl.RegistroModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.Formulario.model.impl.RegistroImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Registro
 * @generated
 */
@ProviderType
public interface RegistroModel extends BaseModel<Registro> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a registro model instance should use the {@link Registro} interface instead.
	 */

	/**
	 * Returns the primary key of this registro.
	 *
	 * @return the primary key of this registro
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this registro.
	 *
	 * @param primaryKey the primary key of this registro
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the registro ID of this registro.
	 *
	 * @return the registro ID of this registro
	 */
	public long getRegistroId();

	/**
	 * Sets the registro ID of this registro.
	 *
	 * @param registroId the registro ID of this registro
	 */
	public void setRegistroId(long registroId);

	/**
	 * Returns the nombre of this registro.
	 *
	 * @return the nombre of this registro
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this registro.
	 *
	 * @param nombre the nombre of this registro
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the email of this registro.
	 *
	 * @return the email of this registro
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this registro.
	 *
	 * @param email the email of this registro
	 */
	public void setEmail(String email);

	@Override
	public Registro cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}